# -*- coding: utf-8 -*-
"""abscript.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lhVsRGRAy9SNoak1A0erEmKZjpwJT6mv
"""

def add(a, b):
 
    # returning sum of a and b
    return a + b