# -*- coding: utf-8 -*-
"""JurrasicAPICall.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e3fSsFJc3wW4HeTyXLlT-MoQzzijVxNx
"""

def JurrasicCall(RequestJurrasic):
  import requests
  import json

  new =requests.post(
      "https://api.ai21.com/studio/v1/j1-jumbo/complete", #sends our request ot the ai21 servers
      headers={"Authorization": "Bearer vc7KLlGzEjqrbyKuJ5lmJXejJCeBVfE2"}, #authorizes use with personal authorization code
      json={
          "prompt": RequestJurrasic,  #prompt. For example a question to the bot
          "numResults": 1,  #number of different results it will return
          "maxTokens": 8,   #max lenght of sentence
          "stopSequences": ["."], #stops whenever it generates a . This will make sure that it doesn't print extra words after the first sentence. (so that it wont print: Jackie Chan is the best actor. He (and then not continue this sentence, because it ran out of tokens)
          "topKReturn": 0,    #If higher, it won't look at the best results, but rather the third best or 4th best (according to K)
          "temperature": 0.0  #How well will the responses fall within the "trained response". Increasing this will result in the responses being more off-topic
      }
  )

  data = new.json()   #stores the response from ai21 into the variable data

  for a in data["completions"]: #reads out the json
      newdata = a               #unpacks json into multidimensional list

    
  return newdata["data"]["text"]   #returns only the response (will exclude stuff not usable for user)