# -*- coding: utf-8 -*-
"""TestScript

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LIg4p_CXZs8PYHfzbbAHHWae9nfjKEPl
"""

def check(check):
  if check == "check":
    return "Everything is in order"
  else:
    return "Something went wrong..."