# -*- coding: utf-8 -*-
"""Translateextra.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qYuwRZA2DJH2pWepwVLoeWDaVGX3TnV0
"""

# Commented out IPython magic to ensure Python compatibility.
def Translate(text_to_translate):
  print("check")
#   %pip install OpenNMT-py
  import onmt
  import sys
  import os
  myFolder ="Software_Engineering"
   
  os.environ['PATH'] += ":/content/drive/MyDrive/" + myFolder + "/CodeRelated/Translation/scripts_local"
  with open('/content/gdrive/MyDrive/Software_Engineering/CodeRelated/Orchestrator/input.txt','r+') as myfile:
    data = myfile.read()
    myfile.seek(0)
    myfile.write(text_to_translate)
    myfile.truncate()

#   %onmt_translate -model /content/gdrive/MyDrive/Software_Engineering/CodeRelated/Translation/EN-NL/model/model_retry_step_100000.pt -src /content/gdrive/MyDrive/Software_Engineering/CodeRelated/Orchestrator/input.txt -output /content/gdrive/MyDrive/Software_Engineering/CodeRelated/Orchestrator/output.txt -gpu 0 -verbose
  
  
  f = open("/content/gdrive/MyDrive/Software_Engineering/CodeRelated/Orchestrator/output.txt", "r")
  sentence = f.read()

  return sentence